### PR TITLE
Implemented BinarySearch in Python

### PR DESCRIPTION
**Pull request by kunal15112001**
# Description

**Please provide a summary of your project or the changes related to the issue.** Include relevant motivation and context to help us understand the purpose and impact of your work.

**List your tech stack and any dependencies that are required for this change.** This information will help us review and integrate your contributions effectively.

## Type of change
- [X] New Project 
- [ ] New Feature 
- [ ] Bug fix

Issue number:

# Checklist:

- [X] I have included a README.md file for my project clearly explaining its purpose, functionality, and usage instructions (applicable for new projects, not bug fixes).
- [X] My code adheres to the style guidelines outlined by this project.
- [X] I have thoroughly reviewed my code to identify and address any potential errors or inconsistencies.
- [X] I have added clear and concise comments to my code, especially in sections that might be challenging to understand at first glance.
- [X] I have reviewed and followed the project's [Contributing Guidelines](CONTRIBUTING.md) to ensure my contribution aligns with the project's requirements.

### CODE REVIEW

**Comment by sudo-parnab** [comment]
Hi @kunal15112001,

Thank you for your contribution. Please note that the PR description does not currently follow the guidelines provided in the project instructions. Kindly close this PR, rewrite the description to include the necessary details, and ensure you reference the related issue number.

Once you've made these changes, feel free to resubmit the PR.

We appreciate your understanding and look forward to reviewing your updated submission.

**Comment by kunal15112001** [comment]
Please highlight the points that PR description is not following so that it will be easier to make improvements. 
Thank you

**Comment by sudo-parnab** [comment]
the points are itself highlighted, a description about your project what it is and how it works and add the issue number you raised in issue section

**Comment by kunal15112001** [comment]
Sure, I will Update my submission.

**Pull request closed without merging**
